#!/bin/bash
# Batch 3: thirty-six A-pose concepts for the families added in
# UnitDatabase+Families.swift ("Batch 3"). Everything here is an original
# design described in words - never a named likeness, because a named god
# once came back from the painter as a photograph of an actor. The style
# asks for painted detail (engraved metal, woven cloth, hair in strands)
# rather than the first rosters' flat cel shading: the 3D models take their
# texture from this drawing. Skips what exists, so it can be rerun after the
# 250-a-day quota.
cd "$(dirname "$0")/../.."
STYLE="Full-body character concept for a stylised mobile gacha RPG in the manner of Summoners War: about five heads tall with a slightly large head, big hands and feet, chunky simplified shapes and a strong readable silhouette, hand-painted textures with fine detail - engraved and embossed metal with worn bright edges, cloth with a visible weave and stitched trim, hair and fur in defined strands, leather with grain - soft natural shading with painted highlights, rich saturated colour, a palette of three main colours plus black and skin. Standing in a relaxed A-pose facing the viewer, feet apart and both feet fully visible, arms lowered a little away from the body with a clear gap between each arm and the torso, anything held kept in one hand tight against the outside of the leg. The whole figure is visible head to toe and centred on a plain flat light-grey background with a plain light-grey floor, soft even studio light, no cast shadows, no text, no frame, one character only."
AVOID="Avoid: realistic proportions, photorealism, a real person or actor, anything standing beside the figure, arms crossed or held in front of the body, a weapon held out away from the body, a cape or cloth flying away from the body, a floor-length robe hiding the feet, wings spread wide, multiple characters, cropping, a dramatic background, text, watermark."
gen() { out="Art/Concepts/$1_sw.png"; [ -s "$out" ] && { echo "have $1"; return; }; python3 tools/genart.py --prompt "$STYLE $2 $AVOID" --out "$out" --size 1024x1024 >/dev/null 2>&1 && echo "ok $1" || echo "FAILED $1"; }

# ---- Egypt
gen ra "The Egyptian sun god as an original cartoon character: a tall falcon-headed man with bronze-gold feathers, a large golden sun disc with a coiled cobra on his brow, a white and gold kilt with a red sash, a wide gold collar inlaid with carnelian, gold vambraces, sandalled feet apart, a slender was-sceptre held upright tight against the outside of his right leg. Palette gold, white, carnelian red."
gen osiris "The Egyptian god of the dead as an original cartoon character: a serene man with smooth green skin, a tall white atef crown with two ostrich plumes, a plaited false beard, wrapped in white linen mummy bindings from the chest to the ankles with a red sash, a wide gold collar, both bandaged feet visible and apart, a gold crook held tight against the outside of his right leg and a flail against the left. Palette white, gold, green."
gen ptah "The Egyptian craftsman god as an original cartoon character: a calm man with a tight lapis-blue skullcap and a straight false beard, wrapped in a close-fitting white shroud from the shoulders to the ankles with a gold collar and a menat counterweight down his back, both sandalled feet visible and apart, a tall was-sceptre with a djed and ankh head held upright tight against the outside of his right leg. Palette white, lapis blue, gold."
gen khnum "The Egyptian ram-headed god as an original cartoon character: a broad heavy-shouldered man with the head of a ram, long curling horizontal horns, a short brown-gold mane, a plain white kilt with a green sash, a wide gold collar, gold armbands, thick legs and sandalled feet apart, a round bronze shield strapped to his left forearm held down at his side and a short mace against the outside of his right leg. Palette gold, white, river green."
gen nephthys "The Egyptian goddess of mourning as an original cartoon character: a slender woman with dark hair under a black and gold headdress shaped like a basket on a house, a long black sheath dress with gold trim ending above the ankles, a wide gold collar, black kite wings folded tight against her back, bare feet apart, empty hands at her sides. Palette black, gold, dusk violet."
gen maat "The Egyptian goddess of truth as an original cartoon character: a poised young woman with a single tall white ostrich feather standing up from a gold headband, black braided hair, a simple white linen dress with a gold and turquoise belt ending above the ankles, a gold collar, white feathered wings folded tight down her back, bare feet apart, a gold ankh held tight against the outside of her right leg. Palette white, gold, turquoise."
gen serqet "The Egyptian scorpion goddess as an original cartoon character: a lithe woman with a gold scorpion crown whose tail arches up over her head, dark hair, a fitted black and gold dress ending above the knees with a segmented gold armour bodice, gold bracers, bare feet apart, a curved dagger held tight against the outside of each leg. Palette black, gold, venom green."
gen taweret "The Egyptian hippopotamus goddess as an original cartoon character: a stout round-bellied standing hippopotamus woman with a friendly fierce face, small ears, a long black wig, a red and gold collar and a gold belt over a green and gold kilt, lion-like paws, thick short legs and broad feet apart, a heavy knotted staff held upright tight against the outside of her right leg. Palette river green, gold, red."
gen anhur "The Egyptian hunter god as an original cartoon character: a tall athletic bearded man with a crown of four tall straight plumes, a short embroidered tunic with a red and gold kilt ending above the knees, a wide gold collar, gold vambraces, sandalled feet apart, a long spear held upright tight against the outside of his right leg and a coiled rope on his belt. Palette red, gold, white."
gen bes "The Egyptian household dwarf god as an original cartoon character: a short stocky bandy-legged dwarf with a broad grinning bearded face, a lion's mane and a tall crown of feathers, his tongue out, a leopard-skin cape over the shoulders that hangs straight down the back, a short red kilt, thick short legs and bare feet apart, a round tambourine held tight against the outside of his right leg and a short curved knife against the left. Palette gold, red, leopard tan."
gen medjay "An Egyptian desert scout as an original cartoon character: a lean dark-skinned young man with short curled hair under a white and red headcloth, a leather cross-belt over a bare chest, a short white kilt with a copper belt, leather bracers, sandalled feet apart, a recurve bow held upright tight against the outside of his left leg and a quiver of arrows on his back. Palette copper, white, red."
gen cobra_priestess "An Egyptian cobra priestess as an original cartoon character: a slim woman with a gold uraeus cobra headdress rising over her brow, a long black wig, a green and gold sheath dress ending above the ankles, a gold collar, bare feet apart, a slender gold and green cobra-headed staff held upright tight against the outside of her right leg. Palette green, gold, black."

# ---- Greece
gen hera "The Greek queen of the gods as an original cartoon character: a regal woman with dark hair piled under a tall gold crown, a long peplos of white and royal blue with gold borders ending above the ankles, a peacock-feather mantle that hangs straight down her back, gold armbands, sandalled feet apart, a tall gold sceptre topped with a small bird held upright tight against the outside of her right leg. Palette white, gold, peacock blue."
gen hephaestus "The Greek smith god as an original cartoon character: a broad barrel-chested bearded man with soot-dark curly hair and a leather smith's cap, a heavy leather apron over a short brown tunic ending above the knees, bronze greaves on both legs and a bronze brace on the right leg, sandalled feet apart, a big square-headed smith's hammer held upright tight against the outside of his right leg. Palette bronze, leather brown, ember orange."
gen demeter "The Greek goddess of the harvest as an original cartoon character: a warm motherly woman with wheat-gold hair braided with grain under a crown of wheat ears, a long green and cream peplos ending above the ankles, a brown shawl that hangs straight down her back, sandalled feet apart, a sheaf of wheat held tight against the outside of her left leg and a short sickle against the right. Palette wheat gold, green, cream."
gen dionysus "The Greek god of wine as an original cartoon character: a young smiling long-haired man with a crown of ivy and grapes, a short purple chiton with gold trim ending above the knees, a leopard skin over one shoulder hanging straight down, gold armbands, sandalled feet apart, a thyrsus staff topped with a pine cone held upright tight against the outside of his right leg and a wine cup in the other hand at his side. Palette purple, gold, ivy green."
gen aphrodite "The Greek goddess of love as an original cartoon character: a graceful woman with long wavy golden hair, a flowing rose-pink and white chiton with a gold girdle ending above the ankles, gold jewellery, a small white dove perched on her right shoulder, bare feet apart, a large scallop shell held tight against the outside of her left leg. Palette rose pink, white, gold."
gen nike "The Greek winged goddess of victory as an original cartoon character: an athletic young woman with short dark hair under a gold laurel wreath, a short white and gold chiton ending above the knees, gold greaves, large white wings folded tight down her back, sandalled feet apart, a short sword held tight against the outside of her right leg and a laurel branch in her left hand at her side. Palette white, gold, laurel green."
gen achilles "A Greek hero of the Trojan War as an original cartoon character: a tall athletic young man with long golden hair under a bronze crested helmet pushed up on his head, a bronze muscled cuirass over a short red tunic ending above the knees, bronze greaves, sandalled feet apart, a tall ash spear held upright tight against the outside of his right leg and a round bronze shield strapped to his left forearm held down at his side. Palette bronze, red, gold."
gen atalanta "A Greek huntress as an original cartoon character: a lean young woman with auburn hair tied back, a short green hunting chiton with a leather belt ending above the knees, a leather bracer, a short brown cloak that hangs straight down her back, laced sandals with both feet apart, a recurve bow held upright tight against the outside of her left leg and a quiver on her back. Palette forest green, leather brown, bronze."
gen siren "A Greek siren as an original cartoon character: a pale woman with long dark seaweed-green hair and small feathered wings folded tight against her back, feathered forearms ending in clawed hands, a teal and silver scaled bodice with a short feathered skirt ending above the knees, bird-like taloned feet apart, a small silver lyre held tight against the outside of her left leg. Palette teal, silver, dark green."
gen nymph "A Greek water nymph as an original cartoon character: a slim young woman with flowing pale-blue hair braided with lilies, a light white and sea-green chiton ending above the knees, a wreath of reeds, bare feet apart, a slender clay water jar held tight against the outside of her left leg. Palette sea green, white, silver."

# ---- Norse
gen baldr "The Norse god of light as an original cartoon character: a handsome young man with shoulder-length golden hair and a short beard, a white and gold tunic with a blue cloak that hangs straight down his back, a gold torc, gold arm rings, fur-trimmed boots apart, a slender white spear held upright tight against the outside of his right leg. Palette white, gold, sky blue."
gen frigg "The Norse queen of the gods as an original cartoon character: a stately woman with long silver-blonde hair in braids under a gold circlet, a long blue and cream gown with gold embroidery ending above the ankles, a falcon-feather cloak that hangs straight down her back, a ring of keys at her belt, soft boots apart, a distaff wound with golden thread held upright tight against the outside of her right leg. Palette blue, cream, gold."
gen surtr "A Norse fire giant as an original cartoon character: a towering muscular giant with charcoal-black cracked skin glowing orange between the cracks, a mane of flame-orange hair and beard, black iron armour plates on the shoulders and chest, a dark leather kilt ending above the knees, iron greaves, bare cracked feet apart, a huge two-handed sword wreathed in fire held upright tight against the outside of his right leg. Palette black, ember orange, iron."
gen njord "The Norse god of the sea as an original cartoon character: a weathered bearded man with grey-blond hair, a sea-green tunic under a fish-scale mail shirt, a blue cloak that hangs straight down his back, a gold torc, rope wound around one forearm, sea boots apart, a long steering oar held upright tight against the outside of his right leg and a round wooden shield strapped to his left forearm held down at his side. Palette sea green, blue, gold."
gen idunn "The Norse goddess of youth as an original cartoon character: a fresh-faced young woman with long red-gold braids and a crown of apple blossom, a green and cream dress with gold trim ending above the ankles, a brown leather apron, soft boots apart, a wooden basket of golden apples held tight against the outside of her left leg. Palette green, cream, gold."
gen sif "A Norse goddess with golden hair as an original cartoon character: a strong young woman with long shining golden hair to her waist, a leather and bronze scale corselet over a red tunic ending above the knees, bronze bracers, a green cloak that hangs straight down her back, fur-trimmed boots apart, a straight sword held tight against the outside of her right leg. Palette gold, red, green."
gen ullr "The Norse god of archery as an original cartoon character: a tall lean bearded man with long ash-blond hair under a fur-lined hood pushed back, a white and grey fur-trimmed tunic ending above the knees, a leather bracer, laced winter boots apart, a tall yew longbow held upright tight against the outside of his left leg and a quiver on his back. Palette white, ice blue, silver."
gen vidar "A silent Norse god of vengeance as an original cartoon character: a huge broad-shouldered man with a stern bearded face and dark hair under an iron cap, a dark green tunic under a heavy leather and iron lamellar coat ending above the knees, iron bracers, one enormous thick-soled leather boot on the right foot and a plain boot on the left, feet apart, a broad iron-shod staff held upright tight against the outside of his right leg. Palette iron, dark green, leather brown."
gen fenrir "A monstrous Norse wolf-man as an original cartoon character: a towering hunched wolf-headed warrior with grey-black fur, yellow eyes and bared fangs, a broken iron chain and shackle around his neck and a shackle with a few broken links on each wrist, a dark leather harness with steel studs over the chest and a ragged fur kilt ending above the knees, clawed feet apart, empty clawed hands at his sides. Palette grey, steel blue, black."
gen bragi "The Norse god of poetry as an original cartoon character: a lean older man with a long flowing white beard and hair, a dark red tunic with gold knotwork under a grey cloak that hangs straight down his back, gold arm rings, soft boots apart, a carved wooden harp held tight against the outside of his left leg. Palette dark red, gold, grey."
gen einherjar "A ghostly Norse warrior of the hall of the slain as an original cartoon character: a broad bearded warrior with pale blue-white skin and glowing eyes, an iron helmet with a nose guard, a ring-mail shirt over a blue tunic ending above the knees, leather bracers, boots apart, a round painted shield strapped to his left forearm held down at his side and an axe held tight against the outside of his right leg. Palette iron, blue, pale gold."
gen shield_maiden "A Norse shield maiden as an original cartoon character: a fierce young woman with blonde braids and blue war paint, a leather and steel-scale corselet over a dark blue tunic ending above the knees, a fur-trimmed cloak that hangs straight down her back, bracers, boots apart, a round red and white painted shield strapped to her left forearm held down at her side and a straight sword held tight against the outside of her right leg. Palette steel, dark blue, red."
gen light_elf "A Norse light elf as an original cartoon character: a slender graceful figure with pale luminous skin, long white hair and pointed ears, a white and pale-gold tunic with leaf embroidery ending above the knees, a short green cloak that hangs straight down the back, bare feet apart, a slender white staff topped with a glowing crystal held upright tight against the outside of the right leg. Palette white, pale gold, leaf green."
gen dark_elf "A Norse dark elf as an original cartoon character: a wiry figure with charcoal-grey skin, white hair pulled back and pointed ears, a black leather jerkin with violet runic trim over dark trousers, a short hooded cloak with the hood down that hangs straight down the back, boots apart, a curved black dagger held tight against the outside of the right leg. Palette black, violet, silver."
echo concepts-batch3-done
