#!/bin/bash
# Thirty-two stylised concepts for the second big roster batch. Four lanes.
cd /home/user/Budget-and-advice
STYLE="Full-body character concept for a stylised mobile gacha RPG in the manner of Summoners War: about five heads tall with a slightly large head, big hands and feet, chunky simplified shapes and a strong readable silhouette, hand-painted cel-shaded textures with crisp highlights, a strict palette of three colours plus black and skin. Standing in a relaxed A-pose facing the viewer, feet apart, arms lowered a little away from the body, any weapon held in one hand tight against the body. The whole figure is visible head to toe and centred on a plain flat light-grey background with a plain light-grey floor, soft even studio light, no cast shadows, no text, no frame, one character only."
AVOID="Avoid: realistic proportions, photorealism, anything standing beside the figure, a cape or cloth flying away from the body, wings spread wide, multiple characters, cropping, a dramatic background, text, watermark."
gen() { out="Art/Concepts/$1_sw.png"; [ -s "$out" ] && { echo "have $1"; return; }; python3 tools/genart.py --prompt "$STYLE $2 $AVOID" --out "$out" --size 1024x1024 >/dev/null 2>&1 && echo "ok $1" || echo "FAILED $1"; }
lane1() {
gen horus "Horus, falcon-headed Egyptian god of the sky: a falcon head with sharp golden eyes and the double crown, a bronze and gold pectoral, a white kilt with gold and turquoise panels, gold bracers, a khopesh held down against his right leg. Palette gold, white, turquoise."
gen isis "Isis, Egyptian goddess: a woman with a gold throne-shaped headdress and a vulture crown, long black hair, a white sheath dress with a gold and turquoise beaded net, a wide gold collar, gold armbands, an ankh sceptre held upright tight against her body. Palette gold, white, turquoise."
gen set "Set, Egyptian god of storms: a tall figure with the Set-animal head, a long curved snout and tall square-tipped ears, red-black skin, a dark red and black kilt with iron plates, iron bracers, a was-sceptre held upright tight against his body. Palette rust red, iron black, dull gold."
gen bastet "Bastet, Egyptian cat goddess: a slender woman with a black cat head and gold earrings, a fitted green and gold dress, a wide gold collar, gold anklets, twin sickle swords held down at her sides against her legs. Palette black, emerald green, gold."
gen sobek "Sobek, Egyptian crocodile god: a heavy figure with a crocodile head, green-grey scaled skin, a bronze chest harness, a dark blue kilt, a round bronze shield strapped flat on his left forearm, a short bronze spear held upright against his right side. Palette bronze, deep blue, mossy green."
gen hathor "Hathor, Egyptian goddess of joy: a woman with cow horns holding a sun disc on her head, long braided hair, a red and gold dress, a gold menat necklace, a sistrum rattle held against her chest. Palette crimson, gold, turquoise."
gen scarab_knight "Scarab Knight, an Egyptian tomb guardian: a stocky armoured warrior whose helmet and chest plate are shaped like a shining blue-green scarab beetle, sandstone-coloured underarmour, a round shield strapped flat on the left forearm, a short mace held against the right leg. Palette iridescent blue-green, sandstone, gold."
gen mummy "Mummy, an Egyptian undead: a bandaged humanoid with linen wrappings hanging loose, dark cracked skin showing through, a gold funerary mask over the face, a broken gold collar, empty hands. Palette linen white, dark brown, gold."
}
lane2() {
gen jackal_warrior "Jackal Warrior, a soldier of Anubis: a lean man wearing a black jackal-head helm with tall ears, a leather and bronze cuirass, a black and gold kilt, a curved dagger held against his right leg, a small bronze buckler on his left forearm. Palette black, bronze, dull gold."
gen athena "Athena, Greek goddess of wisdom and war: a tall woman in a crested bronze Corinthian helmet pushed back to show her face, a white peplos under a bronze breastplate with an owl emblem, a large round shield strapped flat on her left forearm, a short spear held upright against her right side. Palette bronze, white, olive green."
gen poseidon "Poseidon, Greek god of the sea: a powerful bearded man with sea-green hair and beard, a bronze and coral crown, a bare chest with scale-patterned bronze pauldrons, a deep blue wrapped cloth, a trident held upright tight against his body. Palette sea green, deep blue, bronze."
gen hades "Hades, Greek god of the underworld: a pale gaunt man with black hair and a black beard, a dark iron crown, black and violet robes with gold trim hanging close to the body, a two-pronged bident held upright tight against his body. Palette black, violet, dull gold."
gen apollo "Apollo, Greek god of the sun and music: a young clean-shaven man with golden curls and a laurel wreath, a white chiton with gold trim, a gold lyre held against his chest, a quiver on his back. Palette gold, white, sky blue."
gen artemis "Artemis, Greek goddess of the hunt: an athletic young woman with hair tied back, a short green hunting chiton, leather bracers, a silver crescent diadem, a recurved bow held vertically tight against her body, a quiver on her back. Palette forest green, silver, tan leather."
gen hermes "Hermes, Greek messenger god: a lean young man in a winged petasos hat, a short travelling cloak clasped at the shoulder and hanging close, a white tunic, winged sandals, a caduceus staff held upright tight against his body. Palette white, sky blue, gold."
gen minotaur "Minotaur, Greek creature: a huge bull-headed man with wide horns and a nose ring, a massive muscular torso, dark fur on the legs, iron manacles on the wrists, a leather loincloth, a great double axe held against his leg. Palette dark brown, iron, blood red."
}
lane3() {
gen cyclops "Cyclops, Greek giant: a hulking one-eyed brute with a bald head and a single huge eye, a rough leather tunic and belt, bare feet, a wooden club with iron bands held against his leg. Palette grey-green skin, brown leather, iron."
gen amazon "Amazon warrior, Greek: a strong woman with a braided ponytail, a leather and bronze cuirass, a short red chiton, bronze greaves, a crescent shield strapped flat on her left forearm, a double-headed axe held against her right leg. Palette bronze, red, tan leather."
gen medusa "Medusa, Greek gorgon: a woman with a crown of small green snakes for hair, pale green skin, golden eyes, a dark bronze scale bodice, a long dark green skirt, bronze bracers, clawed hands at her sides. Palette green, dark bronze, gold."
gen odin "Odin, Norse all-father: an old bearded man with one eye and an eyepatch, a wide-brimmed dark hat over grey hair, a dark blue cloak hanging close to the body, chainmail under a grey tunic, a spear held upright tight against his body, a raven perched on his shoulder. Palette dark blue, grey, gold."
gen thor "Thor, Norse god of thunder: a huge red-bearded man with a winged iron helmet, a leather and iron cuirass, a red cloak clasped close to the shoulders and hanging straight down behind, iron gauntlets, a short-handled war hammer held down against his right leg. Palette iron, red, gold."
gen freya "Freya, Norse goddess of love and war: a woman with long golden braids, a feathered cloak hanging close to the body, a blue dress under a bronze breastplate, a gold torc, a sword held down against her leg. Palette gold, blue, white."
gen loki "Loki, Norse trickster god: a lean grinning man with slicked-back black hair and a bronze helmet with two long curved horns, a green tunic with gold trim under a dark leather coat, a curved dagger held against his leg. Palette green, gold, black."
gen tyr "Tyr, Norse god of justice: a stern warrior with an iron cap helmet and a short beard, a chainmail shirt under a grey and blue tunic, his right forearm ending in an iron cap where the hand was lost, a round painted shield strapped flat on his left forearm, a longsword in a scabbard at his side. Palette iron, blue, white."
}
lane4() {
gen heimdall "Heimdall, Norse watchman of the gods: a tall man with a gold helmet and a white beard, a white and gold cloak hanging close, a gold breastplate, a great curved horn held against his chest. Palette gold, white, sky blue."
gen hel "Hel, Norse goddess of the dead: a woman whose face and body are half living pale skin and half dark corpse-blue, long black hair, a black and grey gown with silver trim, a silver crown of thorns, hands at her sides. Palette black, corpse blue, silver."
gen skadi "Skadi, Norse giantess of winter: a tall woman in white fur and leather with a fur hood, frost-blue skin, snowshoes on her feet, a recurved bow held vertically tight against her body, a quiver on her back. Palette white fur, ice blue, silver."
gen valkyrie "Valkyrie, Norse warrior maiden: a woman in a winged silver helmet, chainmail under a blue tabard, feathered wings folded down tightly behind her back like a closed cloak, a spear held upright tight against her body, a round shield strapped flat on her left forearm. Palette silver, blue, white."
gen draugr "Draugr, Norse undead warrior: a blue-grey rotting corpse in rusted chainmail and a torn tunic, a horned iron helmet, glowing blue eyes, a notched axe held against his leg, a battered round shield on the left forearm. Palette rusted iron, corpse grey, glowing blue."
gen berserker "Berserker, Norse warrior: a massive bare-chested man wearing a bear-head pelt as a hood and cloak hugging his shoulders, war paint, leather trousers and boots, twin axes held down against his legs. Palette brown fur, iron, blood red."
gen frost_troll "Frost Troll, Norse creature: a hunched bulky troll with pale blue skin, icicle-like tusks, a huge nose, shaggy white fur on the shoulders, a rough leather loincloth, an ice-crusted club held against his leg. Palette ice blue, white fur, grey stone."
gen dwarf_smith "Dwarf Smith, Norse craftsman: a short broad dwarf with a long braided red beard, a leather apron over chainmail, a horned iron helmet, a huge smithing hammer held against his leg, a shield on his back. Palette iron, red, leather brown."
}
lane1 & lane2 & lane3 & lane4 & wait
echo concepts-done
