#!/bin/bash
cd /home/user/Budget-and-advice
STYLE="Full-body character concept for a stylised mobile gacha RPG in the manner of Summoners War: about five heads tall with a slightly large head, big hands and feet, chunky simplified shapes and a strong readable silhouette, hand-painted cel-shaded textures with crisp highlights, a strict palette of three colours plus black and skin. Standing in a relaxed A-pose facing the viewer, feet apart and both feet fully visible, arms lowered a little away from the body with a clear gap between each arm and the torso, any weapon held in one hand tight against the outside of the leg. The whole figure is visible head to toe and centred on a plain flat light-grey background with a plain light-grey floor, soft even studio light, no cast shadows, no text, no frame, one character only."
AVOID="Avoid: realistic proportions, photorealism, a real person or actor, anything standing beside the figure, arms crossed or held in front of the body, a weapon held out away from the body, a cape or cloth flying away from the body, wings spread wide, a floor-length dress hiding the feet, multiple characters, cropping, a dramatic background, text, watermark."
gen() { out="Art/Concepts/$1_sw.png"; python3 tools/genart.py --prompt "$STYLE $2 $AVOID" --out "$out" --size 1024x1024 >/dev/null 2>&1 && echo "ok $1" || echo "FAILED $1"; }
gen loki "An original cartoon Norse trickster god (not any real person): a lean grinning man with slicked-back black hair and a bronze helmet with two long curved horns, a green tunic with gold trim under a dark leather coat that hangs straight down, a curved dagger held against the outside of his right leg. Palette green, gold, black." &
gen bastet "Bastet, Egyptian cat goddess: a slender woman with a black cat head and gold earrings, a fitted green and gold dress ending above the knees, a wide gold collar, gold anklets, bare feet with visible toes, empty open hands at her sides. Palette black, emerald green, gold." &
gen hathor "Hathor, Egyptian goddess of joy: a woman with cow horns holding a sun disc on her head, long braided hair, a red and gold dress with a slit that shows both sandalled feet, a gold menat necklace, a sistrum rattle held down against the outside of her right leg. Palette crimson, gold, turquoise." &
gen boss_jotunn "A Norse frost giant: a huge bearded giant with frost-blue skin, icicles in his beard, a horned iron crown, bear pelts and iron-banded armour, a massive ice-crusted axe held down against the outside of his right leg. Palette frost blue, iron, bear brown." &
gen enemy_sandstone_sentinel "A sandstone sentinel: an animated Egyptian statue of a guardian warrior with a nemes headdress, a cracked sandstone body with glowing blue cracks, a stone shield strapped flat against his left forearm, a stone khopesh held down against the outside of his right leg. Palette sandstone, glowing blue, dull gold." &
wait
echo concepts-redo-done
