#!/bin/bash
# Batch 4: twenty A-pose concepts for the two pantheons added as data on
# 2026-09-11 - Rome (UnitDatabase+Families.swift, `familyRowsRoman`) and the
# Jade Court (`familyRowsChinese`). Everything here is an original design
# described in words - costume, colours, what is held and where - never a
# named likeness, because a named god once came back from the painter as a
# photograph of an actor. The style is batch 3's painted detail (engraved
# metal, woven cloth, hair in strands): the 3D models take their texture from
# this drawing. The two dragons are serpentine Chinese dragons standing on
# four claws in a readable, symmetrical silhouette; Meshy's rigger reads a
# biped, so their rig is a separate question for the day their credits come.
# Skips what exists, so it can be rerun after the 250-a-day quota.
cd "$(dirname "$0")/../.."
STYLE="Full-body character concept for a stylised mobile gacha RPG in the manner of Summoners War: about five heads tall with a slightly large head, big hands and feet, chunky simplified shapes and a strong readable silhouette, hand-painted textures with fine detail - engraved and embossed metal with worn bright edges, cloth with a visible weave and stitched trim, hair and fur in defined strands, leather with grain - soft natural shading with painted highlights, rich saturated colour, a palette of three main colours plus black and skin. Standing in a relaxed A-pose facing the viewer, feet apart and both feet fully visible, arms lowered a little away from the body with a clear gap between each arm and the torso, anything held kept in one hand tight against the outside of the leg. The whole figure is visible head to toe and centred on a plain flat light-grey background with a plain light-grey floor, soft even studio light, no cast shadows, no text, no frame, one character only."
AVOID="Avoid: realistic proportions, photorealism, a real person or actor, anything standing beside the figure, arms crossed or held in front of the body, a weapon held out away from the body, a cape or cloth flying away from the body, a floor-length robe hiding the feet, wings spread wide, multiple characters, cropping, a dramatic background, text, watermark."
# A dragon is not a biped: the same painted style, but the pose is its own.
DRAGON_STYLE="Full-body creature concept for a stylised mobile gacha RPG in the manner of Summoners War: chunky simplified shapes, a strong readable silhouette, hand-painted textures with fine detail - each scale painted, engraved metal on any ornament, mane and whiskers in defined strands - soft natural shading with painted highlights, rich saturated colour, a palette of three main colours plus black. A serpentine Chinese dragon standing on all four clawed feet facing the viewer, the long body raised in one clear S-curve behind the shoulders with the head held high at the front and the tail resting on the floor to one side, all four legs visible and apart with a clear gap between them, nothing overlapping the head or the legs, the whole creature visible from horns to tail and centred on a plain flat light-grey background with a plain light-grey floor, soft even studio light, no cast shadows, no text, no frame, one creature only."
DRAGON_AVOID="Avoid: a Western winged dragon, wings of any kind, a coiled body hiding the legs, the body crossing in front of the head, photorealism, multiple creatures, cropping, a dramatic background, fire or water effects, text, watermark."
gen() { out="Art/Concepts/$1_sw.png"; [ -s "$out" ] && { echo "have $1"; return; }; python3 tools/genart.py --prompt "$STYLE $2 $AVOID" --out "$out" --size 1024x1024 >/dev/null 2>&1 && echo "ok $1" || echo "FAILED $1"; }
dragon() { out="Art/Concepts/$1_sw.png"; [ -s "$out" ] && { echo "have $1"; return; }; python3 tools/genart.py --prompt "$DRAGON_STYLE $2 $DRAGON_AVOID" --out "$out" --size 1024x1024 >/dev/null 2>&1 && echo "ok $1" || echo "FAILED $1"; }

# ---- Rome
gen mars "The Roman god of war as an original cartoon character: a broad heavily built bearded man in a bronze muscled cuirass with an engraved eagle on the chest, a bronze helmet with a tall red horsehair crest pushed up on his head, a red military cloak that hangs straight down his back, a pleated leather strap skirt over a red tunic ending above the knees, bronze greaves, hobnailed sandals with both feet apart, a tall spear held upright tight against the outside of his right leg and a large oval bronze shield strapped to his left forearm held down at his side. Palette bronze, legion red, gold."
gen minerva "The Roman goddess of wisdom as an original cartoon character: a composed woman with dark hair drawn back under a gold Attic helmet with a short crest pushed up on her head, a long white stola with a purple border ending above the ankles under a gold-scaled breastplate, a small brown owl perched on her right shoulder, gold armbands, sandalled feet apart, a slender spear held upright tight against the outside of her right leg and a round bronze shield with a gorgon face strapped to her left forearm held down at her side. Palette white, gold, imperial purple."
gen neptune "The Roman god of the sea and of horses as an original cartoon character: a powerful bearded man with sea-green hair, a wreath of bronze seaweed, a bronze scale cuirass in the shape of fish scales over a teal tunic ending above the knees, a short blue cloak that hangs straight down his back, bronze greaves with horse heads embossed on them, bare feet apart, a bronze trident held upright tight against the outside of his right leg. Palette sea teal, bronze, deep blue."
gen pluto "The Roman god of the underworld and of buried wealth as an original cartoon character: a grave, pale man with a dark beard and a crown of dark gold and black iron, a long black robe with a wide gold border ending above the ankles under a heavy gold pectoral set with silver coins, a black cloak that hangs straight down his back, gold rings on every finger, sandalled feet apart, a two-pronged bident of dark iron held upright tight against the outside of his right leg. Palette black, old gold, silver."
gen diana "The Roman goddess of the moon and the hunt as an original cartoon character: a lean young woman with dark hair in a knot under a silver crescent-moon diadem, a short white hunting tunic with a green border ending above the knees, a leather baldric, a short grey cloak that hangs straight down her back, laced hunting boots with both feet apart, a silver recurve bow held upright tight against the outside of her left leg and a quiver of silver arrows on her back. Palette white, silver, forest green."
gen mercury "The Roman god of trade, travel and thieves as an original cartoon character: a lithe smiling young man with short curly hair under a round winged travelling cap, a short orange tunic with a gold border ending above the knees, a leather money-purse and a coin-scale hanging from his belt, winged sandals with small gold wings at the ankles and both feet apart, a gold caduceus staff with two entwined snakes held upright tight against the outside of his right leg. Palette orange, gold, white."
gen bellona "The Roman goddess of war as an original cartoon character: a fierce tall woman with red hair in a tight plait under a bronze helmet with a black crest pushed up on her head, a bronze cuirass over a dark red tunic ending above the knees, bronze bracers over forearms marked with old ritual scars, a black cloak that hangs straight down her back, greaves, hobnailed boots with both feet apart, a coiled leather war whip held tight against the outside of her left leg and a short sword against the right. Palette blood red, bronze, black."
gen centurion "A Roman centurion as an original cartoon character: a stocky weathered man with a close-cropped beard, a bronze helmet with a transverse red crest pushed up on his head, a mail shirt with bronze medals across the chest over a red tunic ending above the knees, a pleated strap skirt, bronze greaves, hobnailed sandals with both feet apart, a short gladius sword held tight against the outside of his right leg and a knotted vine-stick held tight against the outside of his left leg. Palette red, iron, bronze."
gen gladiator "A Roman gladiator as an original cartoon character: a muscular scarred man with short dark hair, a bronze visored helmet with a fish crest pushed up on his head, one bronze shoulder guard and a padded arm guard on the right arm, a bare chest, a wide leather belt over a short white loincloth ending above the knees, one bronze greave on the left leg, sandalled feet apart, a short gladius held tight against the outside of his right leg and a small square shield strapped to his left forearm held down at his side. Palette bronze, sand, white."
gen vestal "A Roman Vestal priestess as an original cartoon character: a serene young woman with her hair bound in six braids under a white veil that hangs straight down her back, a long plain white stola with a narrow red border ending above the ankles, a white woollen band across her brow, a small red-and-white cord at her waist, sandalled feet apart, a small bronze lamp with a steady flame held tight against the outside of her right leg. Palette white, hearth red, bronze."

# ---- The Jade Court
gen sun_wukong "The Monkey King of Chinese legend as an original cartoon character: a wiry grinning monkey-faced figure with golden-brown fur and bright amber eyes, a gold circlet band around his brow, a phoenix-feather cap with two long pheasant plumes, a short golden chainmail shirt over a red and yellow tunic ending above the knees, a tiger-skin kilt, cloud-stepping boots with both feet apart, a long red and gold iron staff with gold hoops at both ends held upright tight against the outside of his right leg. Palette gold, red, tiger orange."
dragon azure_dragon "The Azure Dragon of the East, guardian of spring, as an original creature design: a long serpentine Chinese dragon with scales of deep azure blue and turquoise fading to a pale jade belly, a flowing dark-blue mane and long whiskers, branching antler-like horns, a golden ridge of spines down the back, four strong legs with gold-clawed feet, small gold rings around each ankle, the body carrying a faint pattern of stars along its flank. Palette azure blue, jade, gold."
gen nezha "The lotus prince of Chinese legend as an original cartoon character: a bright-eyed boy of about twelve with his black hair in two high buns tied with red ribbons, a red silk stomacher and short red and gold jacket over white trousers ending above the ankles, a long red sash that hangs straight down his back, a gold ring worn like a collar, small wheels of fire strapped flat under each foot with both feet apart, a fire-tipped spear held upright tight against the outside of his right leg. Palette red, gold, white."
gen guan_yu "A deified general of the Three Kingdoms as an original cartoon character: a towering dignified man with a very long black beard to his belt and stern brows, a green silk robe with gold embroidery ending above the knees under gold-trimmed lamellar armour, a green scholar's headscarf, green cloth boots with both feet apart, a very tall halberd with a curved blade shaped like a dragon's head held upright tight against the outside of his right leg. Palette jade green, gold, black."
gen chang_e "The Chinese goddess of the moon as an original cartoon character: a graceful woman with long black hair in a high knot with silver moon pins and a few strands falling loose, a flowing pale-blue and white silk robe with wide sleeves and a silver cloud pattern ending above the ankles, a long white silk sash that hangs straight down her back, a small white rabbit sitting on her right shoulder, embroidered slippers with both feet apart, a slender silver moon-disc mirror on a handle held tight against the outside of her left leg. Palette moon silver, pale blue, white."
gen nuwa "The Chinese creator goddess who mended the sky as an original cartoon character: a majestic woman with long black hair under a crown of five glowing stones of five colours, a long robe of yellow and green silk patterned like serpent scales ending above the ankles so both bare feet show apart, a wide sash of five colours that hangs straight down her back, gold armbands, a lump of glowing five-coloured stone held tight against the outside of her right leg and a bronze compass in her left hand at her side. Palette yellow, jade green, five-colour."
dragon dragon_king "The Dragon King of the East Sea as an original creature design: a heavy-bodied serpentine Chinese dragon with scales of deep sea-green and gold, a long white mane and beard, a small gold crown set between two long horns, a jewelled gold collar with a great white pearl at the throat, four thick legs with gold-clawed feet, gold bracelets on each foreleg, a ridge of fin-like spines down the back and a broad fin-edged tail. Palette sea green, gold, pearl white."
gen fox_spirit "A nine-tailed fox spirit of Chinese legend as an original cartoon character: a slender woman with fox ears, silver-white hair to her waist, amber eyes and a knowing smile, a layered red and white silk hanfu robe ending above the knees, nine white fox tails fanned low behind her and kept within the silhouette, a red silk sash that hangs straight down her back, embroidered slippers with both feet apart, a small paper lantern burning with cold blue fire held tight against the outside of her right leg. Palette red, white, silver."
gen jiangshi "A hopping corpse of Chinese legend as an original cartoon character: a stiff greenish-grey figure in a faded dark-blue Qing-dynasty robe with a round mandarin hat, a long yellow paper talisman hanging from the brow over his face, long black nails on stiff hands held slightly away from the body, the robe ending above the ankles so both stiff feet in black boots show apart, a small brass bell tied to his belt. Palette faded blue, grey-green, talisman yellow."
gen terracotta_soldier "A terracotta warrior of the First Emperor's buried army as an original cartoon character: a stocky soldier made entirely of fired grey-brown clay with faint traces of red and green paint, a topknot with a small cloth cap, a knee-length clay tunic with a pattern of armour plates ending above the knees, clay leg wrappings and square-toed shoes with both feet apart, a real bronze halberd with a long shaft held upright tight against the outside of his right leg. Palette terracotta brown, faded red, bronze."
echo concepts-batch4-done
